services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: on-failure
    ports:
      - "1883:1883"
      - "9001:9001"
      
    volumes:
      - ./mosquitto:/etc/mosquitto
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      # - ./mosquitto/passwd:/etc/mosquitto/passwd

    # command: docker exec mosquitto mosquitto_passwd -U /etc/mosquitto/passwd
    # command: mosquitto_passwd -U /etc/mosquitto/passwd
    
    